version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ISIS3710
      DATABASE_PASSWORD: qwerty123
      DATABASE_NAME: parcial2_db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ISIS3710
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: parcial2_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: